[package]
name = "vfs"
version = "0.3.1-alpha.0"
authors = ["Manuel Woelker <github@manuel.woelker.org>"]
description = "A virtual filesystem for Rust"
repository = "https://github.com/manuel-woelker/rust-vfs"
readme = "README.md"
keywords = ["vfs", "virtual",  "filesystem"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
uuid = { version = "0.8", features = ["v4"] }

